apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: pod1
        image: pod1:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "120Mi"
            cpu: "400m"
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: pod1
spec:
  selector:
    app: pod1
  ports:
  - port: 8000
    targetPort: 3000
  externalTrafficPolicy: Local
  type: LoadBalancer